// <auto-generated />
namespace web_deploy_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_atribute3_to_Customer_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_atribute3_to_Customer_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "202201071255395_add_atribute3_to_Customer_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
