// <auto-generated />
namespace web_deploy_1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class feed_genre_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(feed_genre_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202201040131138_feed_genre_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
